# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'descriptiveScoringPage.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_descriptiveScoringPage(object):
    def setupUi(self, descriptiveScoringPage):
        descriptiveScoringPage.setObjectName("descriptiveScoringPage")
        descriptiveScoringPage.resize(1180, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(descriptiveScoringPage.sizePolicy().hasHeightForWidth())
        descriptiveScoringPage.setSizePolicy(sizePolicy)
        descriptiveScoringPage.setStyleSheet("background: #a8d8fd")
        self.layoutWidget = QtWidgets.QWidget(descriptiveScoringPage)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 1148, 761))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.descriptiveProblemNumberLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.descriptiveProblemNumberLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.descriptiveProblemNumberLabel.setStyleSheet("font: 75 12pt \"나눔스퀘어 Bold\";")
        self.descriptiveProblemNumberLabel.setObjectName("descriptiveProblemNumberLabel")
        self.gridLayout.addWidget(self.descriptiveProblemNumberLabel, 3, 0, 1, 1)
        self.descriptive = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.descriptive.setFont(font)
        self.descriptive.setStyleSheet("font: 81 30pt \"나눔스퀘어 ExtraBold\";")
        self.descriptive.setObjectName("descriptive")
        self.gridLayout.addWidget(self.descriptive, 0, 0, 1, 1)
        self.descriptiveNumberListLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.descriptiveNumberListLabel.setStyleSheet("font: 75 13pt \"나눔스퀘어 Bold\";")
        self.descriptiveNumberListLabel.setObjectName("descriptiveNumberListLabel")
        self.gridLayout.addWidget(self.descriptiveNumberListLabel, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox.setStyleSheet("font: 75 10pt \"나눔스퀘어 Bold\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 2, 0, 1, 1)
        self.descriptiveProblemImageLabel = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptiveProblemImageLabel.sizePolicy().hasHeightForWidth())
        self.descriptiveProblemImageLabel.setSizePolicy(sizePolicy)
        self.descriptiveProblemImageLabel.setMinimumSize(QtCore.QSize(630, 360))
        self.descriptiveProblemImageLabel.setMaximumSize(QtCore.QSize(631, 361))
        self.descriptiveProblemImageLabel.setMouseTracking(False)
        self.descriptiveProblemImageLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.descriptiveProblemImageLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.descriptiveProblemImageLabel.setAcceptDrops(False)
        self.descriptiveProblemImageLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.descriptiveProblemImageLabel.setStyleSheet("font: 75 10pt \"나눔스퀘어라운드 Bold\";\n"
"border-color: rgb(85, 0, 0);")
        self.descriptiveProblemImageLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.descriptiveProblemImageLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.descriptiveProblemImageLabel.setObjectName("descriptiveProblemImageLabel")
        self.layoutWidget_3 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(530, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.nextPushButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.nextPushButton.setStyleSheet("background-color: rgb(163, 163, 163);\n"
"font: 75 14pt \"나눔스퀘어라운드 Bold\";\n"
"")
        self.nextPushButton.setObjectName("nextPushButton")
        self.horizontalLayout.addWidget(self.nextPushButton)
        self.layoutWidget_4 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.scroreGridLayout = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.scroreGridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.scroreGridLayout.setContentsMargins(0, 0, 0, 0)
        self.scroreGridLayout.setObjectName("scroreGridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.scroreGridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.scroreGridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.scroreGridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.scroreGridLayout.addItem(spacerItem4, 1, 2, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_2.setStyleSheet("font: 81 15pt \"나눔스퀘어 ExtraBold\";")
        self.label_2.setObjectName("label_2")
        self.scroreGridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.layoutWidget_4)
        self.plainTextEdit_2.setStyleSheet("font: 75 12pt \"나눔스퀘어라운드 Bold\";")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.scroreGridLayout.addWidget(self.plainTextEdit_2, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem5, 2, 1, 1, 1)
        self.ResultPushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResultPushButton.sizePolicy().hasHeightForWidth())
        self.ResultPushButton.setSizePolicy(sizePolicy)
        self.ResultPushButton.setMinimumSize(QtCore.QSize(140, 50))
        self.ResultPushButton.setStyleSheet("font: 81 24pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.ResultPushButton.setObjectName("ResultPushButton")
        self.gridLayout_3.addWidget(self.ResultPushButton, 3, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(1000, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 75 14pt \"나눔스퀘어 Bold\";")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_3.addWidget(self.plainTextEdit, 2, 0, 1, 1)

        self.retranslateUi(descriptiveScoringPage)
        QtCore.QMetaObject.connectSlotsByName(descriptiveScoringPage)

    def retranslateUi(self, descriptiveScoringPage):
        _translate = QtCore.QCoreApplication.translate
        descriptiveScoringPage.setWindowTitle(_translate("descriptiveScoringPage", "Automatic Scoring Program"))
        self.descriptiveProblemNumberLabel.setText(_translate("descriptiveScoringPage", "# 5번"))
        self.descriptive.setText(_translate("descriptiveScoringPage", "서술형"))
        self.descriptiveNumberListLabel.setText(_translate("descriptiveScoringPage", "(서술형 문제 번호: 4, 5, 9)"))
        self.comboBox.setItemText(0, _translate("descriptiveScoringPage", "4"))
        self.comboBox.setItemText(1, _translate("descriptiveScoringPage", "5"))
        self.comboBox.setItemText(2, _translate("descriptiveScoringPage", "9"))
        self.descriptiveProblemImageLabel.setText(_translate("descriptiveScoringPage", "TextLabel"))
        self.nextPushButton.setText(_translate("descriptiveScoringPage", "저장"))
        self.label_2.setText(_translate("descriptiveScoringPage", "- 점수"))
        self.plainTextEdit_2.setPlainText(_translate("descriptiveScoringPage", "     / 15"))
        self.ResultPushButton.setText(_translate("descriptiveScoringPage", "결과 보기"))
        self.label.setText(_translate("descriptiveScoringPage", "- 해설"))
        self.plainTextEdit.setPlainText(_translate("descriptiveScoringPage", "내용을 입력해 주세요."))
