# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'initialSettingPage.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1180, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("background: #a8d8fd")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.descriptive = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptive.sizePolicy().hasHeightForWidth())
        self.descriptive.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.descriptive.setFont(font)
        self.descriptive.setStyleSheet("font: 81 30pt \"나눔스퀘어 ExtraBold\";")
        self.descriptive.setObjectName("descriptive")
        self.gridLayout.addWidget(self.descriptive, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setStyleSheet("font: 12pt \"나눔스퀘어\";")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 0, 1, 1)
        self.descriptiveProblemNumberLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptiveProblemNumberLabel.sizePolicy().hasHeightForWidth())
        self.descriptiveProblemNumberLabel.setSizePolicy(sizePolicy)
        self.descriptiveProblemNumberLabel.setMinimumSize(QtCore.QSize(100, 20))
        self.descriptiveProblemNumberLabel.setStyleSheet("font: 75 15pt \"나눔스퀘어 Bold\";")
        self.descriptiveProblemNumberLabel.setObjectName("descriptiveProblemNumberLabel")
        self.gridLayout.addWidget(self.descriptiveProblemNumberLabel, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setStyleSheet("font: 12pt \"나눔스퀘어\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 9, 0, 1, 1)
        self.descriptiveProblemNumberLabel_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptiveProblemNumberLabel_2.sizePolicy().hasHeightForWidth())
        self.descriptiveProblemNumberLabel_2.setSizePolicy(sizePolicy)
        self.descriptiveProblemNumberLabel_2.setMinimumSize(QtCore.QSize(100, 20))
        self.descriptiveProblemNumberLabel_2.setStyleSheet("font: 75 15pt \"나눔스퀘어 Bold\";")
        self.descriptiveProblemNumberLabel_2.setObjectName("descriptiveProblemNumberLabel_2")
        self.gridLayout.addWidget(self.descriptiveProblemNumberLabel_2, 5, 0, 1, 1)
        self.descriptiveProblemNumberLabel_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptiveProblemNumberLabel_3.sizePolicy().hasHeightForWidth())
        self.descriptiveProblemNumberLabel_3.setSizePolicy(sizePolicy)
        self.descriptiveProblemNumberLabel_3.setMinimumSize(QtCore.QSize(100, 20))
        self.descriptiveProblemNumberLabel_3.setStyleSheet("font: 75 15pt \"나눔스퀘어 Bold\";")
        self.descriptiveProblemNumberLabel_3.setObjectName("descriptiveProblemNumberLabel_3")
        self.gridLayout.addWidget(self.descriptiveProblemNumberLabel_3, 8, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setStyleSheet("font: 12pt \"나눔스퀘어\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 7, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.scroreGridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.scroreGridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.scroreGridLayout.setContentsMargins(0, 0, 0, 0)
        self.scroreGridLayout.setObjectName("scroreGridLayout")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBox.setStyleSheet("font: 75 12pt \"나눔스퀘어 Bold\";")
        self.checkBox.setObjectName("checkBox")
        self.scroreGridLayout.addWidget(self.checkBox, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.scroreGridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.scroreGridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.ResultPushButton_2 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResultPushButton_2.sizePolicy().hasHeightForWidth())
        self.ResultPushButton_2.setSizePolicy(sizePolicy)
        self.ResultPushButton_2.setMinimumSize(QtCore.QSize(140, 50))
        self.ResultPushButton_2.setStyleSheet("font: 81 24pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(83, 138, 255);")
        self.ResultPushButton_2.setObjectName("ResultPushButton_2")
        self.gridLayout_3.addWidget(self.ResultPushButton_2, 2, 1, 1, 1)
        self.ResultPushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResultPushButton.sizePolicy().hasHeightForWidth())
        self.ResultPushButton.setSizePolicy(sizePolicy)
        self.ResultPushButton.setMinimumSize(QtCore.QSize(140, 50))
        self.ResultPushButton.setStyleSheet("font: 81 24pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.ResultPushButton.setObjectName("ResultPushButton")
        self.gridLayout_3.addWidget(self.ResultPushButton, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(760, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Automatic Scoring Program"))
        self.descriptive.setText(_translate("Form", "시험지 초기 설정"))
        self.lineEdit.setText(_translate("Form", "내용을 입력하여 주세요."))
        self.descriptiveProblemNumberLabel.setText(_translate("Form", "시험지 이름"))
        self.lineEdit_3.setText(_translate("Form", "내용을 입력하여 주세요."))
        self.descriptiveProblemNumberLabel_2.setText(_translate("Form", "시험지 장수"))
        self.descriptiveProblemNumberLabel_3.setText(_translate("Form", "시험지 문제수"))
        self.lineEdit_2.setText(_translate("Form", "내용을 입력하여 주세요."))
        self.checkBox.setText(_translate("Form", "OCR 주관식 채점 여부"))
        self.ResultPushButton_2.setText(_translate("Form", "시험지 가져오기"))
        self.ResultPushButton.setText(_translate("Form", "다음"))
