# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resultPage.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_resultPage(object):
    def setupUi(self, resultPage):
        resultPage.setObjectName("resultPage")
        resultPage.resize(1180, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(resultPage.sizePolicy().hasHeightForWidth())
        resultPage.setSizePolicy(sizePolicy)
        resultPage.setStyleSheet("background: #a8d8fd")
        self.layoutWidget = QtWidgets.QWidget(resultPage)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 1133, 751))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.ResultPushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResultPushButton_5.sizePolicy().hasHeightForWidth())
        self.ResultPushButton_5.setSizePolicy(sizePolicy)
        self.ResultPushButton_5.setMinimumSize(QtCore.QSize(140, 50))
        self.ResultPushButton_5.setStyleSheet("font: 81 24pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.ResultPushButton_5.setObjectName("ResultPushButton_5")
        self.gridLayout_17.addWidget(self.ResultPushButton_5, 3, 1, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem = QtWidgets.QSpacerItem(220, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem, 1, 2, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        self.comboBox_5.setMinimumSize(QtCore.QSize(90, 25))
        self.comboBox_5.setStyleSheet("font: 75 12pt \"나눔스퀘어 Bold\";")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_18.addWidget(self.comboBox_5, 1, 3, 1, 1)
        self.studentLabel_5 = QtWidgets.QLabel(self.layoutWidget)
        self.studentLabel_5.setStyleSheet("font: 75 15pt \"나눔스퀘어 Bold\";")
        self.studentLabel_5.setObjectName("studentLabel_5")
        self.gridLayout_18.addWidget(self.studentLabel_5, 1, 0, 1, 1)
        self.StudentNameLabel_5 = QtWidgets.QLabel(self.layoutWidget)
        self.StudentNameLabel_5.setStyleSheet("font: 75 15pt \"나눔스퀘어 Bold\";")
        self.StudentNameLabel_5.setObjectName("StudentNameLabel_5")
        self.gridLayout_18.addWidget(self.StudentNameLabel_5, 1, 1, 1, 1)
        self.testNameLabel_5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testNameLabel_5.sizePolicy().hasHeightForWidth())
        self.testNameLabel_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.testNameLabel_5.setFont(font)
        self.testNameLabel_5.setStyleSheet("font: 81 30pt \"나눔스퀘어 ExtraBold\";")
        self.testNameLabel_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.testNameLabel_5.setObjectName("testNameLabel_5")
        self.gridLayout_18.addWidget(self.testNameLabel_5, 0, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem1, 1, 4, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scoreNameLabel_13 = QtWidgets.QLabel(self.layoutWidget)
        self.scoreNameLabel_13.setStyleSheet("font: 81 15pt \"나눔스퀘어 ExtraBold\";")
        self.scoreNameLabel_13.setObjectName("scoreNameLabel_13")
        self.verticalLayout_5.addWidget(self.scoreNameLabel_13)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(200, 525))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.gridLayout_19.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem2, 0, 1, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.layoutWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_19.addWidget(self.line_9, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem3, 0, 3, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.scoreNameLabel_15 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scoreNameLabel_15.sizePolicy().hasHeightForWidth())
        self.scoreNameLabel_15.setSizePolicy(sizePolicy)
        self.scoreNameLabel_15.setMinimumSize(QtCore.QSize(50, 30))
        self.scoreNameLabel_15.setStyleSheet("font: 81 15pt \"나눔스퀘어 ExtraBold\";")
        self.scoreNameLabel_15.setObjectName("scoreNameLabel_15")
        self.gridLayout_20.addWidget(self.scoreNameLabel_15, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_20.addItem(spacerItem4, 5, 0, 1, 1)
        self.wrongProblemLabel_5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrongProblemLabel_5.sizePolicy().hasHeightForWidth())
        self.wrongProblemLabel_5.setSizePolicy(sizePolicy)
        self.wrongProblemLabel_5.setMinimumSize(QtCore.QSize(110, 30))
        self.wrongProblemLabel_5.setStyleSheet("font: 81 18pt \"나눔스퀘어 ExtraBold\";")
        self.wrongProblemLabel_5.setObjectName("wrongProblemLabel_5")
        self.gridLayout_20.addWidget(self.wrongProblemLabel_5, 3, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_20.addItem(spacerItem5, 2, 0, 1, 1)
        self.myScoreLabel_5 = QtWidgets.QLabel(self.layoutWidget)
        self.myScoreLabel_5.setStyleSheet("font: 81 15pt \"나눔스퀘어 Bold\";")
        self.myScoreLabel_5.setObjectName("myScoreLabel_5")
        self.gridLayout_20.addWidget(self.myScoreLabel_5, 7, 0, 1, 1)
        self.wrongProblemListLabel_5 = QtWidgets.QLabel(self.layoutWidget)
        self.wrongProblemListLabel_5.setStyleSheet("font: 81 15pt \"나눔스퀘어 Bold\";")
        self.wrongProblemListLabel_5.setObjectName("wrongProblemListLabel_5")
        self.gridLayout_20.addWidget(self.wrongProblemListLabel_5, 4, 0, 1, 1)
        self.scoreLabel_5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scoreLabel_5.sizePolicy().hasHeightForWidth())
        self.scoreLabel_5.setSizePolicy(sizePolicy)
        self.scoreLabel_5.setMinimumSize(QtCore.QSize(80, 30))
        self.scoreLabel_5.setStyleSheet("font: 81 18pt \"나눔스퀘어 ExtraBold\";")
        self.scoreLabel_5.setObjectName("scoreLabel_5")
        self.gridLayout_20.addWidget(self.scoreLabel_5, 6, 0, 1, 1)
        self.scoreNameLabel_14 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scoreNameLabel_14.sizePolicy().hasHeightForWidth())
        self.scoreNameLabel_14.setSizePolicy(sizePolicy)
        self.scoreNameLabel_14.setMinimumSize(QtCore.QSize(70, 30))
        self.scoreNameLabel_14.setStyleSheet("font: 81 15pt \"나눔스퀘어 ExtraBold\";")
        self.scoreNameLabel_14.setObjectName("scoreNameLabel_14")
        self.gridLayout_20.addWidget(self.scoreNameLabel_14, 0, 0, 1, 1)
        self.ProblemNumberLabel_5 = QtWidgets.QLabel(self.layoutWidget)
        self.ProblemNumberLabel_5.setMinimumSize(QtCore.QSize(100, 30))
        self.ProblemNumberLabel_5.setStyleSheet("font: 81 15pt \"나눔스퀘어 ExtraBold\";")
        self.ProblemNumberLabel_5.setObjectName("ProblemNumberLabel_5")
        self.gridLayout_20.addWidget(self.ProblemNumberLabel_5, 0, 1, 1, 1)
        self.resultTableView_5 = QtWidgets.QTableView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultTableView_5.sizePolicy().hasHeightForWidth())
        self.resultTableView_5.setSizePolicy(sizePolicy)
        self.resultTableView_5.setMinimumSize(QtCore.QSize(200, 200))
        self.resultTableView_5.setObjectName("resultTableView_5")
        self.gridLayout_20.addWidget(self.resultTableView_5, 1, 0, 1, 3)
        self.gridLayout_19.addLayout(self.gridLayout_20, 0, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem6, 0, 5, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.layoutWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_19.addWidget(self.line_10, 0, 6, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_19, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_17.addItem(spacerItem7, 1, 0, 1, 1)

        self.retranslateUi(resultPage)
        QtCore.QMetaObject.connectSlotsByName(resultPage)

    def retranslateUi(self, resultPage):
        _translate = QtCore.QCoreApplication.translate
        resultPage.setWindowTitle(_translate("resultPage", "Automatic Scoring Program"))
        self.ResultPushButton_5.setText(_translate("resultPage", "엑셀 저장"))
        self.comboBox_5.setItemText(0, _translate("resultPage", "박서연"))
        self.comboBox_5.setItemText(1, _translate("resultPage", "손재호"))
        self.comboBox_5.setItemText(2, _translate("resultPage", "하은영"))
        self.comboBox_5.setItemText(3, _translate("resultPage", "박소영"))
        self.studentLabel_5.setText(_translate("resultPage", "- 학생:"))
        self.StudentNameLabel_5.setText(_translate("resultPage", "박서연"))
        self.testNameLabel_5.setText(_translate("resultPage", "시험지 이름"))
        self.scoreNameLabel_13.setText(_translate("resultPage", "- 문제 처리 결과"))
        self.scoreNameLabel_15.setText(_translate("resultPage", "문제"))
        self.wrongProblemLabel_5.setText(_translate("resultPage", "- 틀린 문제"))
        self.myScoreLabel_5.setText(_translate("resultPage", "95 / 100"))
        self.wrongProblemListLabel_5.setText(_translate("resultPage", "2"))
        self.scoreLabel_5.setText(_translate("resultPage", "- 점수"))
        self.scoreNameLabel_14.setText(_translate("resultPage", "- 문제수: "))
        self.ProblemNumberLabel_5.setText(_translate("resultPage", "100"))
