# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutomaticScoringProgramUI10-2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon, QPixmap


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1191, 801)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 1151, 741))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 2, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(1000, 100))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        self.gridLayout_3.addWidget(self.tableWidget, 2, 0, 1, 1)
        self.ResultPushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResultPushButton.sizePolicy().hasHeightForWidth())
        self.ResultPushButton.setSizePolicy(sizePolicy)
        self.ResultPushButton.setMinimumSize(QtCore.QSize(140, 50))
        self.ResultPushButton.setStyleSheet("font: 81 24pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.ResultPushButton.setObjectName("ResultPushButton")
        self.gridLayout_3.addWidget(self.ResultPushButton, 3, 1, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.descriptiveProblemNumberLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.descriptiveProblemNumberLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.descriptiveProblemNumberLabel.setStyleSheet("font: 75 12pt \"나눔스퀘어 Bold\";")
        self.descriptiveProblemNumberLabel.setObjectName("descriptiveProblemNumberLabel")
        self.gridLayout.addWidget(self.descriptiveProblemNumberLabel, 3, 0, 1, 1)
        self.descriptive = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.descriptive.setFont(font)
        self.descriptive.setStyleSheet("font: 81 30pt \"나눔스퀘어 ExtraBold\";")
        self.descriptive.setObjectName("descriptive")
        self.gridLayout.addWidget(self.descriptive, 0, 0, 1, 1)
        self.descriptiveNumberListLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.descriptiveNumberListLabel.setStyleSheet("font: 75 15pt \"나눔스퀘어 Bold\";")
        self.descriptiveNumberListLabel.setObjectName("descriptiveNumberListLabel")
        self.gridLayout.addWidget(self.descriptiveNumberListLabel, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 2, 0, 1, 1)
        self.descriptiveProblemImageLabel = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptiveProblemImageLabel.sizePolicy().hasHeightForWidth())
        self.descriptiveProblemImageLabel.setSizePolicy(sizePolicy)
        self.descriptiveProblemImageLabel.setMinimumSize(QtCore.QSize(630, 360))
        self.descriptiveProblemImageLabel.setMaximumSize(QtCore.QSize(631, 361))
        self.descriptiveProblemImageLabel.setMouseTracking(False)
        self.descriptiveProblemImageLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.descriptiveProblemImageLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.descriptiveProblemImageLabel.setAcceptDrops(False)
        self.descriptiveProblemImageLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.descriptiveProblemImageLabel.setStyleSheet("font: 75 10pt \"나눔스퀘어라운드 Bold\";\n"
"border-color: rgb(85, 0, 0);")
        self.descriptiveProblemImageLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.descriptiveProblemImageLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.descriptiveProblemImageLabel.setObjectName("descriptiveProblemImageLabel")
        self.layoutWidget_3 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.beforePushButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.beforePushButton.setStyleSheet("background-color: rgb(163, 163, 163);\n"
"font: 75 14pt \"나눔스퀘어라운드 Bold\";\n"
"")
        self.beforePushButton.setObjectName("beforePushButton")
        self.horizontalLayout.addWidget(self.beforePushButton)
        spacerItem1 = QtWidgets.QSpacerItem(468, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.nextPushButton = QtWidgets.QPushButton(self.layoutWidget_3)
        self.nextPushButton.setStyleSheet("background-color: rgb(163, 163, 163);\n"
"font: 75 14pt \"나눔스퀘어라운드 Bold\";\n"
"")
        self.nextPushButton.setObjectName("nextPushButton")
        self.horizontalLayout.addWidget(self.nextPushButton)
        self.layoutWidget_4 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.scroreGridLayout = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.scroreGridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.scroreGridLayout.setContentsMargins(0, 0, 0, 0)
        self.scroreGridLayout.setObjectName("scroreGridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.scroreGridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.ScoreLineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScoreLineEdit.sizePolicy().hasHeightForWidth())
        self.ScoreLineEdit.setSizePolicy(sizePolicy)
        self.ScoreLineEdit.setMinimumSize(QtCore.QSize(220, 20))
        self.ScoreLineEdit.setStyleSheet("font: 75 12pt \"나눔스퀘어 Bold\";")
        self.ScoreLineEdit.setText("")
        self.ScoreLineEdit.setObjectName("ScoreLineEdit")
        self.scroreGridLayout.addWidget(self.ScoreLineEdit, 2, 1, 1, 2)
        self.scoreLabel = QtWidgets.QLabel(self.layoutWidget_4)
        self.scoreLabel.setEnabled(True)
        self.scoreLabel.setMaximumSize(QtCore.QSize(81, 41))
        self.scoreLabel.setAcceptDrops(False)
        self.scoreLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scoreLabel.setStyleSheet("font: 81 20pt \"나눔스퀘어 ExtraBold\";")
        self.scoreLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scoreLabel.setObjectName("scoreLabel")
        self.scroreGridLayout.addWidget(self.scoreLabel, 2, 3, 1, 1)
        self.scoreNameLabel = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scoreNameLabel.sizePolicy().hasHeightForWidth())
        self.scoreNameLabel.setSizePolicy(sizePolicy)
        self.scoreNameLabel.setMinimumSize(QtCore.QSize(50, 30))
        self.scoreNameLabel.setStyleSheet("font: 81 20pt \"나눔스퀘어 ExtraBold\";")
        self.scoreNameLabel.setObjectName("scoreNameLabel")
        self.scroreGridLayout.addWidget(self.scoreNameLabel, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.scroreGridLayout.addItem(spacerItem3, 1, 2, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 140, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.scroreGridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.scroreGridLayout.addItem(spacerItem5, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(1000, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 3, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "점수"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "5"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "?"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "?"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Form", "?"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.ResultPushButton.setText(_translate("Form", "결과 보기"))
        self.descriptiveProblemNumberLabel.setText(_translate("Form", "# 1번"))
        self.descriptive.setText(_translate("Form", "서술형"))
        self.descriptiveNumberListLabel.setText(_translate("Form", "- 서술형 문제 번호: 1, 4, 5"))


        # TODO: 서술형 이미지 가져와야함. list로 설정
        pixmap0 = QPixmap("zebree1.jpg")
        pixmap1 = QPixmap("zebree2.jpg")
        pixmap2 = QPixmap("zebree3.jpg")
        pixmap3 = QPixmap("zebree3.jpg")
        pixmapList = [pixmap0, pixmap1, pixmap2, pixmap3]
        currentPosition = 0

        self.descriptiveProblemImageLabel.setPixmap(QPixmap(pixmapList[currentPosition]))
        # self.descriptiveProblemImageLabel.show()

        self.beforePushButton.setText(_translate("Form", "< 이전"))
        self.beforePushButton.clicked.connect(lambda: self.setdescriptionImageBefore(currentPosition, pixmapList))

        self.nextPushButton.setText(_translate("Form", "다음 >"))
        self.nextPushButton.clicked.connect(lambda: self.setdescriptionImageNext(currentPosition, pixmapList))

        self.comboBox.setItemText(0, _translate("Form", "1"))
        self.comboBox.setItemText(1, _translate("Form", "4"))
        self.comboBox.setItemText(2, _translate("Form", "5"))
        self.descriptiveProblemImageLabel.setText(_translate("Form", "TextLabel"))
        self.beforePushButton.setText(_translate("Form", "< 이전"))
        self.nextPushButton.setText(_translate("Form", "다음 >"))
        self.scoreLabel.setText(_translate("Form", "/15"))
        self.scoreNameLabel.setText(_translate("Form", "점수"))

    def setdescriptionImageBefore(self, currentPosition, p):
        print('c', currentPosition)
        if currentPosition != 0:
            currentPosition = currentPosition - 1
            print(currentPosition)
            self.descriptiveProblemImageLabel.setPixmap(QPixmap(p[currentPosition]))
            return currentPosition
        if currentPosition == 0:
            self.descriptiveProblemImageLabel.setPixmap(QPixmap(p[currentPosition]))
            return 0

    def setdescriptionImageNext(self, currentPosition, p):
        print('c', currentPosition)
        if currentPosition < len(p)-1:
            currentPosition = currentPosition + 1
            print(currentPosition)
            self.descriptiveProblemImageLabel.setPixmap(QPixmap(p[currentPosition]))
            return currentPosition
        if currentPosition >= len(p)-1:
            print(currentPosition)
            self.descriptiveProblemImageLabel.setPixmap(QPixmap(p[currentPosition]))
            return 0


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
