# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AutomaticScoringProgramUI10-1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1190, 760)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(800, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 1, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.descriptiveProblemNumberLabel = QtWidgets.QLabel(self.layoutWidget)
        self.descriptiveProblemNumberLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.descriptiveProblemNumberLabel.setStyleSheet("font: 75 12pt \"나눔스퀘어 Bold\";")
        self.descriptiveProblemNumberLabel.setObjectName("descriptiveProblemNumberLabel")
        self.gridLayout.addWidget(self.descriptiveProblemNumberLabel, 3, 0, 1, 1)
        self.descriptive = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.descriptive.setFont(font)
        self.descriptive.setStyleSheet("font: 81 30pt \"나눔스퀘어 ExtraBold\";")
        self.descriptive.setObjectName("descriptive")
        self.gridLayout.addWidget(self.descriptive, 0, 0, 1, 1)
        self.descriptiveNumberListLabel = QtWidgets.QLabel(self.layoutWidget)
        self.descriptiveNumberListLabel.setStyleSheet("font: 75 15pt \"나눔스퀘어 Bold\";")
        self.descriptiveNumberListLabel.setObjectName("descriptiveNumberListLabel")
        self.gridLayout.addWidget(self.descriptiveNumberListLabel, 1, 0, 1, 1)
        self.descriptiveProblemImageLabel = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptiveProblemImageLabel.sizePolicy().hasHeightForWidth())
        self.descriptiveProblemImageLabel.setSizePolicy(sizePolicy)
        self.descriptiveProblemImageLabel.setMinimumSize(QtCore.QSize(630, 360))
        self.descriptiveProblemImageLabel.setMaximumSize(QtCore.QSize(631, 361))
        self.descriptiveProblemImageLabel.setMouseTracking(False)
        self.descriptiveProblemImageLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.descriptiveProblemImageLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.descriptiveProblemImageLabel.setAcceptDrops(False)
        self.descriptiveProblemImageLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.descriptiveProblemImageLabel.setStyleSheet("font: 75 10pt \"나눔스퀘어라운드 Bold\";\n"
"border-color: rgb(85, 0, 0);")
        self.descriptiveProblemImageLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.descriptiveProblemImageLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.descriptiveProblemImageLabel.setObjectName("descriptiveProblemImageLabel")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.beforePushButton = QtWidgets.QPushButton(self.widget)
        self.beforePushButton.setStyleSheet("background-color: rgb(163, 163, 163);\n"
"font: 75 14pt \"나눔스퀘어라운드 Bold\";\n"
"")
        self.beforePushButton.setObjectName("beforePushButton")
        self.horizontalLayout.addWidget(self.beforePushButton)
        spacerItem3 = QtWidgets.QSpacerItem(468, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.nextPushButton = QtWidgets.QPushButton(self.widget)
        self.nextPushButton.setStyleSheet("background-color: rgb(163, 163, 163);\n"
"font: 75 14pt \"나눔스퀘어라운드 Bold\";\n"
"")
        self.nextPushButton.setObjectName("nextPushButton")
        self.horizontalLayout.addWidget(self.nextPushButton)
        self.widget1 = QtWidgets.QWidget(self.splitter_2)
        self.widget1.setObjectName("widget1")
        self.scroreGridLayout = QtWidgets.QGridLayout(self.widget1)
        self.scroreGridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.scroreGridLayout.setContentsMargins(0, 0, 0, 0)
        self.scroreGridLayout.setObjectName("scroreGridLayout")
        self.ScoreLineEdit = QtWidgets.QLineEdit(self.widget1)
        self.ScoreLineEdit.setStyleSheet("font: 75 12pt \"나눔스퀘어 Bold\";")
        self.ScoreLineEdit.setObjectName("ScoreLineEdit")
        self.scroreGridLayout.addWidget(self.ScoreLineEdit, 2, 1, 1, 2)
        self.scoreNameLabel = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scoreNameLabel.sizePolicy().hasHeightForWidth())
        self.scoreNameLabel.setSizePolicy(sizePolicy)
        self.scoreNameLabel.setMinimumSize(QtCore.QSize(50, 30))
        self.scoreNameLabel.setStyleSheet("font: 81 20pt \"나눔스퀘어 ExtraBold\";")
        self.scoreNameLabel.setObjectName("scoreNameLabel")
        self.scroreGridLayout.addWidget(self.scoreNameLabel, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(110, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.scroreGridLayout.addItem(spacerItem4, 1, 2, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.scroreGridLayout.addItem(spacerItem5, 1, 0, 1, 1)
        self.scoreLabel = QtWidgets.QLabel(self.widget1)
        self.scoreLabel.setEnabled(True)
        self.scoreLabel.setMaximumSize(QtCore.QSize(81, 41))
        self.scoreLabel.setAcceptDrops(False)
        self.scoreLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scoreLabel.setStyleSheet("font: 81 20pt \"나눔스퀘어 ExtraBold\";")
        self.scoreLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scoreLabel.setObjectName("scoreLabel")
        self.scroreGridLayout.addWidget(self.scoreLabel, 2, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.scroreGridLayout.addItem(spacerItem6, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.scroreGridLayout.addItem(spacerItem7, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.ResultPushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResultPushButton.sizePolicy().hasHeightForWidth())
        self.ResultPushButton.setSizePolicy(sizePolicy)
        self.ResultPushButton.setMinimumSize(QtCore.QSize(140, 50))
        self.ResultPushButton.setStyleSheet("font: 81 24pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.ResultPushButton.setObjectName("ResultPushButton")
        self.gridLayout_3.addWidget(self.ResultPushButton, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.descriptiveProblemNumberLabel.setText(_translate("Form", "# 5번"))
        self.descriptive.setText(_translate("Form", "서술형"))
        self.descriptiveNumberListLabel.setText(_translate("Form", "- 서술형 문제 번호: 4, 5"))
        self.descriptiveProblemImageLabel.setText(_translate("Form", "TextLabel"))
        self.beforePushButton.setText(_translate("Form", "< 이전"))
        self.nextPushButton.setText(_translate("Form", "다음 >"))
        self.ScoreLineEdit.setText(_translate("Form", "부분점수"))
        self.scoreNameLabel.setText(_translate("Form", "점수"))
        self.scoreLabel.setText(_translate("Form", "/15"))
        self.ResultPushButton.setText(_translate("Form", "결과 보기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
